# Generated by Django 5.2.4 on 2025-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
